#! /usr/bin/bash

sudo pacman -S wine-staging --noconfirm
sudo pacman -S giflib --noconfirm
sudo pacman -S lib32-giflib --noconfirm
sudo pacman -S libpng --noconfirm
sudo pacman -S lib32-libpng --noconfirm
sudo pacman -S libldap --noconfirm
sudo pacman -S lib32-libldap --noconfirm
sudo pacman -S gnutls --noconfirm
sudo pacman -S lib32-gnutls --noconfirm
sudo pacman -S mpg123 --noconfirm
sudo pacman -S lib32-mpg123 --noconfirm
sudo pacman -S openal --noconfirm
sudo pacman -S lib32-openal --noconfirm
sudo pacman -S v4l-utils --noconfirm
sudo pacman -S lib32-v4l-utils --noconfirm
sudo pacman -S libpulse --noconfirm
sudo pacman -S lib32-libpulse --noconfirm
sudo pacman -S libgpg-error --noconfirm
sudo pacman -S lib32-libgpg-error --noconfirm
sudo pacman -S alsa-plugins --noconfirm
sudo pacman -S lib32-alsa-plugins --noconfirm
sudo pacman -S alsa-lib --noconfirm
sudo pacman -S lib32-alsa-lib --noconfirm
sudo pacman -S libjpeg-turbo --noconfirm
sudo pacman -S lib32-libjpeg-turbo --noconfirm
sudo pacman -S sqlite --noconfirm
sudo pacman -S lib32-sqlite --noconfirm
sudo pacman -S libxcomposite --noconfirm
sudo pacman -S lib32-libxcomposite --noconfirm
sudo pacman -S libxinerama --noconfirm
sudo pacman -S lib32-libgcrypt --noconfirm
sudo pacman -S libgcrypt --noconfirm
sudo pacman -S lib32-libxinerama --noconfirm
sudo pacman -S ncurses --noconfirm
sudo pacman -S lib32-ncurses --noconfirm
sudo pacman -S opencl-icd-loader --noconfirm
sudo pacman -S lib32-opencl-icd-loader --noconfirm
sudo pacman -S libxslt --noconfirm
sudo pacman -S lib32-libxslt --noconfirm
sudo pacman -S libva --noconfirm
sudo pacman -S lib32-libva --noconfirm
sudo pacman -S gtk3 --noconfirm
sudo pacman -S lib32-gtk3 --noconfirm
sudo pacman -S gst-plugins-base-libs --noconfirm
sudo pacman -S lib32-gst-plugins-base-libs --noconfirm
sudo pacman -S vulkan-icd-loader --noconfirm
sudo pacman -S lib32-vulkan-icd-loader --noconfirm

sudo pacman -S lib32-gnutls --noconfirm
sudo pacman -S lib32-libldap --noconfirm
sudo pacman -S lib32-libgpg-error --noconfirm
sudo pacman -S lib32-sqlite --noconfirm
sudo pacman -S lib32-libpulse --noconfirm
